apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue
    version: v-${BUILD_NUMBER}

  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - image: mohab5897/reactapp-blue:${BUILD_NUMBER}
          name: blue
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}