apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
    version: v-${BUILD_NUMBER}
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - image: mohab5897/reactapp-green:${BUILD_NUMBER}
          name: green
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources: {}